### ISSUE TITLE
Customize ConnectionFactoryOptions

### ISSUE THREAD

**Issue by marcelmojzis** [apache/pekko-persistence-r2dbc#169]
It would be helpful to have a way to customize ConnectionFactoryOptions in createConnectionFactory just before the connection factory is created. This would allow, for example, specifying a dynamic password supplier for PostgreSQL connections. If this sounds useful, I can work on a PR.

**Comment by pjfanning** [comment]
@marcelmojzis if you can create a PR that would be great.

**Comment by ptrdom** [comment]
@marcelmojzis IIUC what you want to implement, I think I added it in https://github.com/apache/pekko-persistence-r2dbc/pull/170 with the following code:
https://github.com/apache/pekko-persistence-r2dbc/blob/9644425eb256bdbde4f4ced0b45afc6e8d2be93e/core/src/main/scala/org/apache/pekko/persistence/r2dbc/R2dbcSettings.scala#L182-L196
Once the PR is merged the feature will be available for you to use, so maybe this helps to not duplicate efforts.

**Comment by pjfanning** [comment]
@marcelmojzis if you think that #170 does not address your needs, feel free to still do your own PR.

**Comment by ptrdom** [comment]
> My use case is a bit more complex and can’t be addressed with static settings in the configuration file.

Aha, well if you need password generation during `ActorSystem` runtime, then yeah, config would not work, but if you only need a password generated on startup then you could still do it through dynamic config.

**Comment by marcelmojzis** [comment]
> > My use case is a bit more complex and can’t be addressed with static settings in the configuration file.
> 
> Aha, well if you need password generation during `ActorSystem` runtime, then yeah, config would not work, but if you only need a password generated on startup then you could still do it through dynamic config.

Unfortunately, it is the former
