### ISSUE TITLE
Implement `deleteObject(persistenceId: String, revision: Long)` properly

### ISSUE THREAD

**Issue by mdedetrich** [apache/pekko-persistence-r2dbc#18]
As discussed in https://github.com/apache/incubator-pekko-persistence-r2dbc/pull/8#discussion_r1158930062, the current implementation of `deleteObject(persistenceId: String, revision: Long)` just defers to `deleteObject(persistenceId: String)` (which means it ignores the revision).

The implementation should instead be improved so it only deletes correct revision.

**Comment by pjfanning** [comment]
@mdedetrich do you want this in 1.0.0?

**Comment by mdedetrich** [comment]
> @mdedetrich do you want this in 1.0.0?
Should go in `1.1.0`

**Comment by pjfanning** [comment]
#92 merged
