### ISSUE TITLE
migration module is not published for Scala 3

### ISSUE THREAD

**Issue by pjfanning** [apache/pekko-persistence-r2dbc#83]
https://github.com/apache/incubator-pekko-persistence-r2dbc/blob/main/project/Dependencies.scala#L100

pekko-persistence-jdbc is a test dependency - this does not support Scala 3 yet and when it does it will be a 1.1.0 release

I think the simplest is just to upgrade to pekko-persistence-jdbc 1.1.0 when released.

Alternatives include testing a Scala 3 build but use the pekko-persistence-jdbc_2.13 jar.

`cross CrossVersion.for3Use2_13` in sbt

**Comment by pjfanning** [comment]
wdyt @mdedetrich @raboof @He-Pin @Roiocam @samueleresca @gmethvin @nvollmar ?

**Comment by raboof** [comment]
I might not have all context, but from what I've seen I'd lean towards upgrading to pekko-persistence-jdbc 1.1.0 when released. Is there any particular downside to that approach?

`CrossVersion.for3Use2_13` is great for 'leaf' projects but can lead to problems 'downstream' when used in libraries: for example when the transitive library releases a version for Scala 3 but the library using `for3Use2_13` is still using the cross-built version, a project could get in trouble trying to load both. Also I'm not sure how moving from using `for3Use2_13` to not using `for3Use2_13` in a later version might impact binary compatibility.

**Comment by pjfanning** [comment]
1.1 snapshots support this - https://repository.apache.org/content/groups/snapshots/org/apache/pekko/pekko-persistence-r2dbc-migration_3/
